refactor: configure run python-test
feat: test first approximation

feat: add mako requirement due eox-theming req

feat:try import backend from plugins-settings deps

try to import plugin settings from external plugins.
this to use their default config.

Revert "feat:try import backend from plugins-settings deps"

This reverts commit 493ed7d8975d598aac0b3a2b1113e0670a813065.

This revert is due the impossiblity to import backend settings from
for example eox-theming due they dont have defined plugin settings
from test settings. So the default backends are not imported, is the same.

https://github.com/eduNEXT/eox-theming/blob/master/eox_theming/settings/test.py#L45

**error**:
```
  File "/home/johanc/test/eox-nelp/venv/lib/python3.8/site-packages/eox_theming/edxapp_wrapper/configuration_helpers.py", line 9, in get_configuration_helper
    backend_function = settings.EOX_THEMING_CONFIGURATION_HELPER_BACKEND
  File "/home/johanc/test/eox-nelp/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'EOX_THEMING_CONFIGURATION_HELPER_BACKEND'
make: *** [Makefile:56: python-test] Error 1
```

style: style test backends

refactor!: change and order test and common settings

refactor!: order settings for project

feat: add first test for eox-info

chore: remove unused settings in coverage

by the moment this files are not used but maybe in the future for the production
and devstack settings.

refactor: test for eox-info view

Also changed the way the commit is presented for eox info
view content. removed the `'\b,\n,\r`
Binary with decode and the other with rstrip.

Based on eox-support
https://github.com/eduNEXT/eox-support/blob/master/eox_support/views.py#L16
https://github.com/eduNEXT/eox-support/blob/master/eox_support/tests/test_views.py

chore: remove unnecessary definitions

This due pr recommendation

chore: change test config helpers to mock

refactor: change name for eox-info views